version: '3'

services:
  postgres-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    expose:
      - ${PG_PORT}

  app-server:
    restart: always
    image: luci3942/ip-pavlov-server
    expose:
      - ${SERVER_PORT}
    depends_on:
      - "postgres-server"
    tty: true
    volumes:
      - /app/Images

  client:
    image: luci3942/ip-pavlov-client
    expose:
      - ${CLIENT_PORT}

  nginx:
    depends_on:
      - app-server
      - client
    image: luci3942/ip-pavlov-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf